### ISSUE TITLE
ip -o link does not work

### ISSUE THREAD

**Issue by yoctozepto** [cirros-dev/cirros#54] opened 2020-03-06 08:46 UTC
Some testing scripts we run in Tempest rely on availability of -o in ip command which stands for 'oneline' and makes ip output parsing much more pleasant and reliable.
It seems to have worked with 0.4.0 but gone with 0.5.0 - empty output.
Try e.g.
ip link
vs
ip -o link

EDIT: seemingly only ip -o link fails

**Comment by jharbott** [comment] 2020-03-06 09:56
That must be a regression in busybox, which provides /sbin/ip for both releases. v1.23.2 vs. v1.29.3. As a workaround we could install the iproute2 original, not sure how much impact that would have on the size.

**Comment by jharbott** [comment] 2020-03-06 10:29
The issue is fixed in busybox >= 1.31.0: https://git.busybox.net/busybox/commit/?id=bb3a9531b28f5c946452b92c8ac5a0951c5eab03

**Comment by hrw** [comment] 2020-03-06 11:47
I am for enabling iproute2. This way CirrOS gets same networking tool as most of distros. Image may get more use in neutron.

**Comment by yoctozepto** [comment] 2020-03-06 12:14
I am with hrw. We have some decent kernel, let's have decent basic toolkits.

**Comment by hrw** [comment] 2020-03-06 12:31
Buildroot rootfs grows by ~12% (table in KB):

arch | before | after
-|-|-
aarch64 | 11252 | 12628
x86-64 | 12176|13604

**Closed** 2020-03-06 17:58 UTC
