### ISSUE TITLE
cirros-cloud.net is down

### ISSUE THREAD

**Issue by yoctozepto** [cirros-dev/cirros#12] opened 2020-01-16 13:09 UTC
Reporting issue here due to lack of a better place: cirros-cloud.net is down

**Comment by smoser** [comment] 2020-01-16 16:11
@yoctozepto 

The problem is known and mostly understood at this point.  It happened back in december, but seems to be creeping up again.
 * cirros-cloud.net is hosted with a shared hosting plan by
   [dreamhost.com](https://dreamhost.com).  As part of the shared hosting, the account is limited to a number of simultaneous connections (unconfirmed).  The limit is enforced per ip version (ipv4 or ipv6) and http or https. 
 * This isn't normally an issue, but when it is, your requests basically get
   queued behind image download requests of others and time-out.  The problem
really occurs when someone's automated test is running and repeatedly
downloading images.  Generally the issue only occurs over http/ipv4.

The **easiest workaround** for you is to **use *either* https *or* ipv6**.

The solution is one or more of the following:
 * Me set up download.cirros-cloud.net to redirect to files on github, rather
   than deliving the files itself.  This is just a thing that I have to sit down and do.
 * The infrastructure that is causing the load could use a caching http proxy
   which would make it dramatically faster for them, and avoid this issue for others.
   (This is especially slow because the downloads are trans-pacific and do not get good bandwidth).

I just want to be clear, that I'm not unhappy with dreamhost.  I pay a *very*
small amount per month for "unlimited transfer", download.cirros-cloud.net is
does > 100k hits/day and 90GB/day of transfer.

**Comment by yoctozepto** [comment] 2020-01-16 16:48
Thanks, @smoser for this level of insight. Pity I did not check whether either used http or https but surely both IPv4 and IPv6 were overloaded at the time. Probably opendev Zuul ran out of luck and just massively blocked the server. :-)

**Comment by lucioseki** [comment] 2020-01-16 17:38
@smoser Do you know if the number of simultaneous connections limit for https is greater than the limit for http? And/or the limit for ipv6 is greater than the limit for ipv4?

If so, whilie the CI maintainers don't set up the cache, we could change this url from http to https: https://github.com/openstack/devstack/blob/master/stackrc#L702

... supposing that majority of cirros users are DevStack scripts.

**Comment by yoctozepto** [comment] 2020-01-16 17:46
We are now debugging the issue with Clark. It seems infra has cirros cached but only 0.4.0. Some current jobs use very old releases of cirros, the problem can be amended by using cirros 0.4.0

**Comment by mnaser** [comment] 2020-01-18 03:49
@smoser I'd be happy to host the files on the @vexxhost object storage at no cost which doesn't have any limits similar to that.

I can provide you with an OpenStack project where you can upload them to and then you could perhaps do redirects if this comes up again?

**Comment by smoser** [comment] 2020-01-23 14:26
@mnaser Thanks for the offer.  I think that the goal of getting stuff onto github will be the best solution here.  Then we'll even benefit from the CDN (I assume they have one).  Assuming we can get all the content that we want over here, i think that is best. But thanks for the offer and I may come back to you.

I'm going to close this for now.

In summary, if you have issues with download.cirros-cloud.net:

 a.) Caching proxies are nice if you're using http
 b.) Try using https or ipv6
 c.) feel free to ping me via email or freenode \#cirros
 d.) we do hope to get this fixed, and dreamhost really does do a good job.

**Closed** 2020-01-23 14:27 UTC
